baseurl = "https://fxisco.github.io"
title = "Francisco Payés"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "fpayes"

[params]
    author = "Francisco Payés"
    info = "Web developer and code ranger"
    description = "John Doe's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "/imgs/profile.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Stay curious!"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/fxisco/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/fpayes11/"

# Menu links
[[menu.main]]
    name = "Portofolio"
    weight = 1
    url = "/portofolio/"
